routes/web.php
<?php

use App\Http\Controllers\anggotakeluargaController;
use App\Http\Controllers\authController;
use App\Http\Controllers\clusterController;
use App\Http\Controllers\dashboardController;
use App\Http\Controllers\iuranwargaController;
use App\Http\Controllers\KKwargaController;
use App\Http\Controllers\laporaniuranController;
use App\Http\Controllers\metodepembayaranController;
use App\Http\Controllers\pencarianController;
use App\Http\Controllers\penggunaController;
use App\Http\Controllers\perumahanController;
use App\Http\Controllers\profilController;
use App\Http\Controllers\registrasiController;
use App\Http\Controllers\rumahController;
use App\Http\Controllers\rumahwargaController;
use App\Http\Controllers\transaksiiuranController;
use App\Http\Controllers\wargaController;
use App\Models\perumahanModel;
use App\Models\wargaModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::middleware("guest")->group(function () {
    Route::get('/', [authController::class, "login"])->name("login");
    Route::post('authentication', [authController::class, "store"])->name("login.authentication");

    Route::get('registrasi/formulir_1', [registrasiController::class, 'form_1'])->name('registrasi.form_1');
    Route::post('registrasi/formulir_1', [registrasiController::class, 'store_1'])->name('registrasi.store_1');

    Route::get('registrasi/formulir_2', [registrasiController::class, 'form_2'])->name('registrasi.form_2');
    Route::post('registrasi/formulir_2', [registrasiController::class, 'store_2'])->name('registrasi.store_2');

    Route::get('registrasi/formulir_3', [registrasiController::class, 'form_3'])->name('registrasi.form_3');
    Route::post('registrasi/formulir_3', [registrasiController::class, 'store_3'])->name('registrasi.store_3');

    Route::get('registrasi/formulir_4', [registrasiController::class, 'form_4'])->name('registrasi.form_4');
    Route::post('registrasi/formulir_4', [registrasiController::class, 'store_4'])->name('registrasi.store_4');
});

Route::middleware(['auth', 'konfirmasi'])->group(function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('/dashboardV1', [dashboardController::class, 'dashboardV1'])->name("dashboardV1");
        Route::get('/akses_kepengurusan', [dashboardController::class, 'akses_kepengurusan'])->name("akses.kepengurusan");
        Route::get('/akses_warga', [dashboardController::class, 'akses_warga'])->name("akses.warga");

        Route::resource('warga', wargaController::class);
        Route::get('/warga/{id_kartu_keluarga}/create', [wargaController::class, 'create'])->name("warga.create_spesifik");
        Route::post('/warga_export/dokumen', [wargaController::class, 'export_dokumen_warga'])->name("warga.export_dokumen");
        Route::post('/warga_export/data', [wargaController::class, 'export_data_warga'])->name("warga.export_data");

        Route::resource('cluster', clusterController::class)->except(["show"]);

        Route::resource('perumahan', perumahanController::class)->except(["show"]);

        Route::resource('kartu_keluarga_warga', KKwargaController::class)->parameters([
            'kartu_keluarga_warga' => 'kartu_keluarga',
        ]);

        Route::get('/rumah_warga/{id_kartu_keluarga}/create', [rumahwargaController::class, 'create'])->name("rumah_warga.create");
        Route::post('/rumah_warga/{id_kartu_keluarga}', [rumahwargaController::class, 'store'])->name("rumah_warga.store");
        Route::get('/rumah_warga/{id_rumah}/{id_kartu_keluarga}/edit', [rumahwargaController::class, 'edit'])->name("rumah_warga.edit");
        Route::put('/rumah_warga/{id_rumah}/{id_kartu_keluarga}', [rumahwargaController::class, 'update'])->name("rumah_warga.update");
        Route::delete('/rumah_warga/{id_rumah}/{id_kartu_keluarga}', [rumahwargaController::class, 'destroy'])->name("rumah_warga.destroy");

        Route::resource('metode_pembayaran', metodepembayaranController::class);

        Route::get('/iuran_warga', [iuranwargaController::class, 'index'])->name("iuran_warga.index");
        Route::get('/iuran_warga/{transaksi_iuran}', [iuranwargaController::class, 'show'])->name("iuran_warga.show");
        Route::get('/konfirmasi_iuran_warga/{transaksi_iuran}/{warga}/{status_iuran?}', [iuranwargaController::class, 'update'])->name("konfirmasi_iuran_warga.edit");

        Route::get('/pencarian', [pencarianController::class, 'index'])->name("pencarian.index");
        Route::post('/pencarian', [pencarianController::class, 'store'])->name("pencarian.store");
        Route::get('/pencarian/{warga}/result/{id_perumahan?}', [pencarianController::class, 'result_search'])->name("pencarian.search_rumah");
        Route::post('/pencarian/{warga}/result', [pencarianController::class, 'result_search_post'])->name("pencarian.search");
        Route::get('/pencarian/{transaksi_iuran}', [pencarianController::class, 'show'])->name("pencarian.show");
        Route::get('/konfirmasi_iuran/{transaksi_iuran}/{status_iuran?}/{warga?}/{perumahan?}', [pencarianController::class, 'update_status_iuran'])->name("pencarian.update_status_iuran");

        Route::get('/laporan_iuran', [laporaniuranController::class, 'index'])->name("laporan_iuran.index");
        Route::post('/laporan_iuran/laporan_tahunan', [laporaniuranController::class, 'laporan_tahunan'])->name("laporan_iuran.laporan_tahunan");
        Route::get('/laporan_iuran/laporan_tahunan/export', [laporaniuranController::class, 'laporan_tahunan_export'])->name("laporan_iuran.laporan_tahunan_export");
        Route::post('/laporan_iuran/laporan_bulanan', [laporaniuranController::class, 'laporan_bulanan'])->name("laporan_iuran.laporan_bulanan");

        Route::resource('pengguna', penggunaController::class);
        Route::get('/konfirmasi_pengguna/{pengguna}/{status_akun?}', [penggunaController::class, 'update_status_akun'])->name("pengguna.update_status_akun");
    });

    Route::get("profil/{pengguna}", [profilController::class, "index"])->name("profil.index");
    Route::put("profil/{pengguna}", [profilController::class, "update"])->name("profil.update");

    Route::middleware(['warga'])->group(function () {
        Route::get('/dashboardV2', [dashboardController::class, 'dashboardV2'])->name("dashboardV2");
        Route::post('/daftar_rumah_warga', [dashboardController::class, 'daftar_rumah_warga'])->name("daftar.rumah_warga");

        Route::resource('rumah', rumahController::class)->parameters([
            'rumah' => 'perumahan',
        ]);

        Route::resource('anggota_keluarga', anggotakeluargaController::class)->parameters([
            'anggota_keluarga' => 'warga',
        ]);
        Route::get("kartu_keluarga/{kartu_keluarga}/edit", [anggotakeluargaController::class, "edit_kartu_keluarga"])->name("kartu_keluarga.edit");
        Route::put("kartu_keluarga/{kartu_keluarga}", [anggotakeluargaController::class, "update_kartu_keluarga"])->name("kartu_keluarga.update");

        Route::resource('transaksi_iuran', transaksiiuranController::class);
        Route::post('rekening-dropdown', [transaksiiuranController::class, 'getRekening'])->name('rekening-dropdown');
        Route::get("transaksi_iuran_bulan/{bulan}/{tahun}/{id_perumahan}", function ($bulan, $tahun, $id_perumahan) {

            $warga = wargaModel::where("id_warga", session()->get('auth_data.0.id_warga'))->first();
            $perumahan = perumahanModel::with("cluster")->where("id_perumahan", $id_perumahan)->get();

            if (empty($warga)) {
                $warga = wargaModel::where("id_kartu_keluarga", session()->get('auth_data.0.id_kartu_keluarga'))->where("status_hubungan_keluarga", "Kepala Keluarga")->firstOrFail();
            }

            return view("pengguna.transaksi_iuran.create_option", compact("bulan", "tahun", "perumahan", "warga"));
        })->name("transaksi_iuran_bulan");
    });

    Route::post('/logout', [authController::class, "logout"])->name("logout");
});

Route::get("clear_data", function (Request $request) {
    $request->session()->flush();

    return redirect()->back();
});

app/Http/Controllers/penggunaController.php
<?php

namespace App\Http\Controllers;

use App\Models\kartukeluargaModel;
use App\Models\penggunaModel;
use App\Models\wargaModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class penggunaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pengguna = penggunaModel::with("kartukeluarga")->get();

        return view("kepengurusan.pengguna.index", compact("pengguna"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pengguna = new penggunaModel();
        $kartu_keluarga = kartukeluargaModel::where("id_kartu_keluarga", "!=", "1")->get();

        $model_form = [
            "model" => "create",
            "submit" => "Simpan",
            "btn" => "btn-success",
        ];

        return view("kepengurusan.pengguna.create", compact("pengguna", "kartu_keluarga", "model_form"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->jabatan == "Lain-lain") {
            $request->validate([
                "no_kk" => "required|max:16|min:16",
                "id_kartu_keluarga" => "required|unique:pengguna,id_kartu_keluarga",
                "nama_pengguna" => "required",
                "jabatan" => "required",
                "jabatan_lain" => "required",
                "kata_sandi" => "required",
                "peran" => "required",
            ]);
            $jabatan = $request->jabatan_lain;
        } else {
            $request->validate([
                "no_kk" => "required|max:16|min:16",
                "id_kartu_keluarga" => "required|unique:pengguna,id_kartu_keluarga",
                "nama_pengguna" => "required",
                "jabatan" => "required",
                "kata_sandi" => "required",
                "peran" => "required",
            ]);
            $jabatan = $request->jabatan;
        }

        $pengguna = [
            "id_kartu_keluarga" => $request->id_kartu_keluarga,
            "nama_pengguna" => $request->nama_pengguna,
            "nama_lengkap" => $request->nama_lengkap,
            "kata_sandi" => Hash::make($request->kata_sandi),
            "peran" => $request->peran,
            "jabatan" => $jabatan,
        ];

        penggunaModel::create($pengguna);

        return redirect()->route("pengguna.index")->withToastSuccess('Berhasil Menyimpan Data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $pengguna = penggunaModel::findOrFail($id);

        $query_warga = wargaModel::query();
        $warga = wargaModel::with("kartukeluarga", "kartukeluarga.perumahan", "kartukeluarga.perumahan.cluster")
            ->where("id_kartu_keluarga", $pengguna->id_kartu_keluarga)
            ->where("status_hubungan_keluarga", "Kepala Keluarga")
            ->first();

        $jumlah_warga = $query_warga->clone()->where("id_kartu_keluarga", $pengguna->id_kartu_keluarga)->count();

        if (empty($warga)) {
            return redirect()->back()->withToastWarning('Tidak Ada Data Yang Ditampilkan');
        }
        return view("kepengurusan.pengguna.show", compact("pengguna", "warga", "jumlah_warga"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pengguna = penggunaModel::with("kartukeluarga")->findOrFail($id);
        $kartu_keluarga = kartukeluargaModel::where("id_kartu_keluarga", "!=", "1")->get();
        $model_form = [
            "model" => "edit",
            "submit" => "Ubah",
            "btn" => "btn-warning",
        ];

        return view("kepengurusan.pengguna.edit", compact("pengguna", "kartu_keluarga", "model_form"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, penggunaModel $pengguna)
    {
        if ($request->jabatan == "Lain-lain") {
            $jabatan = $request->jabatan_lain;
        } else {
            $jabatan = $request->jabatan;
        }

        if (!empty($request->ganti_password)) {
            $request->validate([
                "no_kk" => "required|max:16|min:16",
                "id_kartu_keluarga" => "required|unique:pengguna,id_kartu_keluarga," . $request->old_id_kartu_keluarga . ",id_kartu_keluarga",
                "nama_pengguna" => "required",
                "kata_sandi" => "required",
                "peran" => "required",
                "status_pengguna" => "required",
            ]);

            $pengguna->update([
                "id_kartu_keluarga" => $request->id_kartu_keluarga,
                "nama_pengguna" => $request->nama_pengguna,
                "kata_sandi" => Hash::make($request->kata_sandi),
                "jabatan" => $jabatan,
                "peran" => $request->peran,
                "status_pengguna" => $request->status_pengguna,
            ]);

        } else {
            $request->validate([
                "no_kk" => "required|max:16|min:16",
                "id_kartu_keluarga" => "required|unique:pengguna,id_kartu_keluarga," . $request->old_id_kartu_keluarga . ",id_kartu_keluarga",
                "nama_pengguna" => "required",
                "peran" => "required",
                "status_pengguna" => "required",
            ]);

            $pengguna->update([
                "id_kartu_keluarga" => $request->id_kartu_keluarga,
                "nama_pengguna" => $request->nama_pengguna,
                "peran" => $request->peran,
                "jabatan" => $jabatan,
                "status_pengguna" => $request->status_pengguna,
            ]);
        }

        return redirect()->route("pengguna.index")->withToastSuccess('Berhasil Mengubah Data');
    }

    public function update_status_akun(Request $request)
    {
        $id_pengguna = $request->segment(2);
        $status_akun = $request->segment(3);

        if ($id_pengguna) {
            $update_pengguna = penggunaModel::findOrFail($id_pengguna);

            $update_pengguna->update([
                "status_akun" => $status_akun,
            ]);

            return redirect()->back()->withToastSuccess('Berhasil Mengubah Status');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(penggunaModel $pengguna)
    {
        try {
            $pengguna->delete();
        } catch (\Throwable$th) {
            return redirect()->route("pengguna.index")->withToastWarning('Terdapat kesalahan saat menghapus data');
        }
        return redirect()->route("pengguna.index")->withToastSuccess('Berhasil Menghapus Data');
    }
}

resources/views/pengguna/rumah/create.blade.php
@extends("layouts.app")

@section('title', 'Tambah Perumahan')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Form Tambah Data Perumahan Green Semanggi Mangrove
    </p>
    <form action="{{ route('rumah.store') }}" method="POST" novalidate>
        @csrf
        @include("pengguna.rumah._form")
    </form>
@endsection

resources/views/pengguna/rumah/edit.blade.php
@extends("layouts.app")

@section('title', 'Ubah Perumahan')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Form Ubah Data Perumahan Green Semanggi Mangrove
    </p>
    <form action="{{ route('rumah.update', $rumah->id_perumahan) }}" method="POST" novalidate>
        @method("PUT")
        @csrf
        @include("pengguna.rumah._form")
    </form>
@endsection

resources/views/pengguna/rumah/index.blade.php
@extends("layouts.app")

@section('title', 'Daftar Perumahan')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Halaman Pengelolaan Data Perumahan Green Semanggi Mangrove
    </p>
    <div class="card">
        <div class="card-body">
            <div class="form-row">
                <div class="form-group col-md-3">
                    <a href="{{ route('rumah.create') }}" class="btn btn-block btn-icon icon-left btn-success">
                        <i class="fas fa-plus-circle"></i> Tambah Data Perumahan
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div style="overflow: hidden;">
                        <table class="table table-striped" id="datatables">
                            <thead>
                                <tr>
                                    <th>Perumahan</th>
                                    <th>Kepemilikan Rumah</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($perumahan->perumahan as $data_perumahan)
                                    <tr>
                                        <td>{{ $data_perumahan->cluster->nama_cluster }} {{ $data_perumahan->blok_perumahan }}-{{ $data_perumahan->nama_perumahan }}</td>
                                        <td>{{ $data_perumahan->kepemilikan_rumah }}</td>
                                        <td>
                                            <div class="d-block"></div>
                                            @if ($data_perumahan->kepemilikan_rumah == 'Kontrak/Sewa')
                                                <a href="#" class="btn btn-sm btn-icon icon-left btn-info btn-lihat" data-toggle="modal" data-target=".modal-detail" data-perumahan="{{ $data_perumahan->nama_cluster }} {{ $data_perumahan->blok_perumahan }}-{{ $data_perumahan->nama_perumahan }}" data-kepemilikan_rumah="{{ $data_perumahan->kepemilikan_rumah }}" data-periode_kontrak="{{ $data_perumahan->periode_kontrak }}" data-periode_waktu="{{ $data_perumahan->periode_waktu }}" data-tanggal_mulai_kontrak="{{ $data_perumahan->tanggal_mulai_kontrak }}" data-tanggal_akhir_kontrak="{{ $data_perumahan->tanggal_akhir_kontrak }}">
                                                    <i class="far fa-eye"></i> Lihat
                                                </a>
                                            @else
                                                <a href="#" class="btn btn-sm btn-icon icon-left btn-info btn-lihat disabled">
                                                    <i class="far fa-eye"></i> Lihat
                                                </a>
                                            @endif
                                            <a href="{{ route('rumah.edit', $data_perumahan->id_perumahan) }}" class="btn btn-sm btn-icon icon-left btn-warning mr-1">
                                                <i class="far fa-edit "></i> Ubah
                                            </a>
                                            <form style="all: unset" action="{{ route('rumah.destroy', $data_perumahan->id_perumahan) }}" id="form_delete_perumahan_{{ $data_perumahan->id_perumahan }}" data-id="{{ $data_perumahan->cluster->nama_cluster }} {{ $data_perumahan->blok_perumahan }}-{{ $data_perumahan->nama_perumahan }}" method="POST">
                                                @method("DELETE")
                                                @csrf
                                                <button type="button" onclick="deleteconfirmPerumahan('form_delete_perumahan_{{ $data_perumahan->id_perumahan }}')" class="btn btn-sm btn-icon icon-left btn-danger"><i class="far fa-trash-alt"></i>Hapus</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('modal')
    <div class="modal fade modal-detail" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Detail Perumahan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body modal-ktp">
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <tr>
                                <th class="w-50">Perumahan</th>
                                <td class="w-50 text-left" id="perumahan">null</td>
                            </tr>
                            <tr>
                                <th>Kepemilikan Rumah</th>
                                <td class="w-50 text-left" id="kepemilikan_rumah">null</td>
                            </tr>
                            <tr>
                                <th>Periode Kontrak/Sewa</th>
                                <td class="w-50 text-left" id="periode_kontrak">null</td>
                            </tr>
                            <tr>
                                <th>Tanggal Mulai Kontrak</th>
                                <td class="w-50 text-left" id="tanggal_mulai">null</td>
                            </tr>
                            <tr>
                                <th>Tanggal Akhir Kontrak</th>
                                <td class="w-50 text-left" id="tanggal_akhir">null</td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css-library')
    <link rel="stylesheet" href="{{ asset('assets/modules/datatables/datatables.min.css') }}">
@endpush

@push('js-library')
    <script src="{{ asset('assets/modules/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('assets/modules/sweetalert/sweetalert.min.js') }}"></script>
@endpush

@push('js-template')
    <script>
        $(document).ready(function() {
            $("#datatables").dataTable({
                responsive: true,
                paging: true,
                ordering: true,
                info: true,
                filter: true,
                length: true,
                processing: true,
                deferRender: true,
                autoWidth: false,
                language: {
                    url: "{{ asset('assets/modules/datatables/lang/id.json') }}"
                },
                columnDefs: [{
                        targets: -1,
                        visible: true,
                    },
                    {
                        "width": "28%",
                        "targets": -1,
                    },
                    {
                        orderable: false,
                        targets: -1,
                    },
                ],
            });

            $(".btn-lihat").click(function() {
                var perumahan = $(this).data("perumahan");
                var kepemilikan_rumah = $(this).data("kepemilikan_rumah");
                var periode_kontrak = $(this).data("periode_kontrak");
                var periode_waktu = $(this).data("periode_waktu");
                var tanggal_mulai_kontrak = $(this).data("tanggal_mulai_kontrak");
                var tanggal_akhir_kontrak = $(this).data("tanggal_akhir_kontrak");

                if (periode_waktu == "years") {
                    var periode = "Tahun";
                } else {
                    var periode = "Bulan";
                };

                var opsi = {
                    day: 'numeric',
                    weekday: 'long',
                    month: 'long',
                    year: 'numeric',
                };
                const convert_mulai = new Date(tanggal_mulai_kontrak);
                const convert_akhir = new Date(tanggal_akhir_kontrak);

                var mulai = convert_mulai.toLocaleDateString("id", opsi);
                var akhir = convert_akhir.toLocaleDateString("id", opsi);
                $("#perumahan").text(perumahan);
                $("#kepemilikan_rumah").text(kepemilikan_rumah);
                $("#periode_kontrak").text(periode_kontrak + " " + periode);
                $("#tanggal_mulai").text(mulai);
                $("#tanggal_akhir").text(akhir);
            });
        });

        function deleteconfirmPerumahan(form) {
            var id = $('#' + form).attr('data-id');
            swal({
                title: 'Apakah Anda Yakin Menghapus data : ' + id + '?',
                text: 'Anda Tidak Akan Dapat Mengembalikannya!',
                icon: 'warning',
                buttons: ["Batal", "Ya, Hapus Data!"],
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#' + form).submit();
                }
            });
        }
    </script>
@endpush