routes/web.php
<?php

use App\Http\Controllers\anggotakeluargaController;
use App\Http\Controllers\authController;
use App\Http\Controllers\clusterController;
use App\Http\Controllers\dashboardController;
use App\Http\Controllers\iuranwargaController;
use App\Http\Controllers\KKwargaController;
use App\Http\Controllers\laporaniuranController;
use App\Http\Controllers\metodepembayaranController;
use App\Http\Controllers\pencarianController;
use App\Http\Controllers\penggunaController;
use App\Http\Controllers\perumahanController;
use App\Http\Controllers\profilController;
use App\Http\Controllers\registrasiController;
use App\Http\Controllers\rumahController;
use App\Http\Controllers\rumahwargaController;
use App\Http\Controllers\transaksiiuranController;
use App\Http\Controllers\wargaController;
use App\Models\perumahanModel;
use App\Models\wargaModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Route::middleware("guest")->group(function () {
    Route::get('/', [authController::class, "login"])->name("login");
    Route::post('authentication', [authController::class, "store"])->name("login.authentication");

    Route::get('registrasi/formulir_1', [registrasiController::class, 'form_1'])->name('registrasi.form_1');
    Route::post('registrasi/formulir_1', [registrasiController::class, 'store_1'])->name('registrasi.store_1');

    Route::get('registrasi/formulir_2', [registrasiController::class, 'form_2'])->name('registrasi.form_2');
    Route::post('registrasi/formulir_2', [registrasiController::class, 'store_2'])->name('registrasi.store_2');

    Route::get('registrasi/formulir_3', [registrasiController::class, 'form_3'])->name('registrasi.form_3');
    Route::post('registrasi/formulir_3', [registrasiController::class, 'store_3'])->name('registrasi.store_3');

    Route::get('registrasi/formulir_4', [registrasiController::class, 'form_4'])->name('registrasi.form_4');
    Route::post('registrasi/formulir_4', [registrasiController::class, 'store_4'])->name('registrasi.store_4');
});

Route::middleware(['auth', 'konfirmasi'])->group(function () {
    Route::middleware(['auth'])->group(function () {
        Route::get('/dashboardV1', [dashboardController::class, 'dashboardV1'])->name("dashboardV1");
        Route::get('/akses_kepengurusan', [dashboardController::class, 'akses_kepengurusan'])->name("akses.kepengurusan");
        Route::get('/akses_warga', [dashboardController::class, 'akses_warga'])->name("akses.warga");

        Route::resource('warga', wargaController::class);
        Route::get('/warga/{id_kartu_keluarga}/create', [wargaController::class, 'create'])->name("warga.create_spesifik");
        Route::post('/warga_export/dokumen', [wargaController::class, 'export_dokumen_warga'])->name("warga.export_dokumen");
        Route::post('/warga_export/data', [wargaController::class, 'export_data_warga'])->name("warga.export_data");

        Route::resource('cluster', clusterController::class)->except(["show"]);

        Route::resource('perumahan', perumahanController::class)->except(["show"]);

        Route::resource('kartu_keluarga_warga', KKwargaController::class)->parameters([
            'kartu_keluarga_warga' => 'kartu_keluarga',
        ]);

        Route::get('/rumah_warga/{id_kartu_keluarga}/create', [rumahwargaController::class, 'create'])->name("rumah_warga.create");
        Route::post('/rumah_warga/{id_kartu_keluarga}', [rumahwargaController::class, 'store'])->name("rumah_warga.store");
        Route::get('/rumah_warga/{id_rumah}/{id_kartu_keluarga}/edit', [rumahwargaController::class, 'edit'])->name("rumah_warga.edit");
        Route::put('/rumah_warga/{id_rumah}/{id_kartu_keluarga}', [rumahwargaController::class, 'update'])->name("rumah_warga.update");
        Route::delete('/rumah_warga/{id_rumah}/{id_kartu_keluarga}', [rumahwargaController::class, 'destroy'])->name("rumah_warga.destroy");

        Route::resource('metode_pembayaran', metodepembayaranController::class);

        Route::get('/iuran_warga', [iuranwargaController::class, 'index'])->name("iuran_warga.index");
        Route::get('/iuran_warga/{transaksi_iuran}', [iuranwargaController::class, 'show'])->name("iuran_warga.show");
        Route::get('/konfirmasi_iuran_warga/{transaksi_iuran}/{warga}/{status_iuran?}', [iuranwargaController::class, 'update'])->name("konfirmasi_iuran_warga.edit");

        Route::get('/pencarian', [pencarianController::class, 'index'])->name("pencarian.index");
        Route::post('/pencarian', [pencarianController::class, 'store'])->name("pencarian.store");
        Route::get('/pencarian/{warga}/result/{id_perumahan?}', [pencarianController::class, 'result_search'])->name("pencarian.search_rumah");
        Route::post('/pencarian/{warga}/result', [pencarianController::class, 'result_search_post'])->name("pencarian.search");
        Route::get('/pencarian/{transaksi_iuran}', [pencarianController::class, 'show'])->name("pencarian.show");
        Route::get('/konfirmasi_iuran/{transaksi_iuran}/{status_iuran?}/{warga?}/{perumahan?}', [pencarianController::class, 'update_status_iuran'])->name("pencarian.update_status_iuran");

        Route::get('/laporan_iuran', [laporaniuranController::class, 'index'])->name("laporan_iuran.index");
        Route::post('/laporan_iuran/laporan_tahunan', [laporaniuranController::class, 'laporan_tahunan'])->name("laporan_iuran.laporan_tahunan");
        Route::get('/laporan_iuran/laporan_tahunan/export', [laporaniuranController::class, 'laporan_tahunan_export'])->name("laporan_iuran.laporan_tahunan_export");
        Route::post('/laporan_iuran/laporan_bulanan', [laporaniuranController::class, 'laporan_bulanan'])->name("laporan_iuran.laporan_bulanan");

        Route::resource('pengguna', penggunaController::class);
        Route::get('/konfirmasi_pengguna/{pengguna}/{status_akun?}', [penggunaController::class, 'update_status_akun'])->name("pengguna.update_status_akun");
    });

    Route::get("profil/{pengguna}", [profilController::class, "index"])->name("profil.index");
    Route::put("profil/{pengguna}", [profilController::class, "update"])->name("profil.update");

    Route::middleware(['warga'])->group(function () {
        Route::get('/dashboardV2', [dashboardController::class, 'dashboardV2'])->name("dashboardV2");
        Route::post('/daftar_rumah_warga', [dashboardController::class, 'daftar_rumah_warga'])->name("daftar.rumah_warga");

        Route::resource('rumah', rumahController::class)->parameters([
            'rumah' => 'perumahan',
        ]);

        Route::resource('anggota_keluarga', anggotakeluargaController::class)->parameters([
            'anggota_keluarga' => 'warga',
        ]);
        Route::get("kartu_keluarga/{kartu_keluarga}/edit", [anggotakeluargaController::class, "edit_kartu_keluarga"])->name("kartu_keluarga.edit");
        Route::put("kartu_keluarga/{kartu_keluarga}", [anggotakeluargaController::class, "update_kartu_keluarga"])->name("kartu_keluarga.update");

        Route::resource('transaksi_iuran', transaksiiuranController::class);
        Route::post('rekening-dropdown', [transaksiiuranController::class, 'getRekening'])->name('rekening-dropdown');
        Route::get("transaksi_iuran_bulan/{bulan}/{tahun}/{id_perumahan}", function ($bulan, $tahun, $id_perumahan) {

            $warga = wargaModel::where("id_warga", session()->get('auth_data.0.id_warga'))->first();
            $perumahan = perumahanModel::with("cluster")->where("id_perumahan", $id_perumahan)->get();

            if (empty($warga)) {
                $warga = wargaModel::where("id_kartu_keluarga", session()->get('auth_data.0.id_kartu_keluarga'))->where("status_hubungan_keluarga", "Kepala Keluarga")->firstOrFail();
            }

            return view("pengguna.transaksi_iuran.create_option", compact("bulan", "tahun", "perumahan", "warga"));
        })->name("transaksi_iuran_bulan");
    });

    Route::post('/logout', [authController::class, "logout"])->name("logout");
});

Route::get("clear_data", function (Request $request) {
    $request->session()->flush();

    return redirect()->back();
});

resources/views/kepengurusan/warga/create.blade.php
@extends("layouts.app")

@section('title', 'Tambah Warga')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Form Tambah Data Warga Green Semanggi Mangrove
    </p>
    <div class="alert alert-primary alert-has-icon">
        <div class="alert-icon"><i class="far fa-lightbulb"></i></div>
        <div class="alert-body">
            <div class="alert-title">Info</div>
            Jika tidak menemukan No. KK silahkan melakukan tambah data KK di <a href="{{ route('kartu_keluarga_warga.create') }}" class="badge badge-info">link ini</a>
        </div>
    </div>
    <form action="{{ route('warga.store') }}" method="POST" enctype="multipart/form-data" novalidate>
        @csrf
        @include("kepengurusan.warga._form")
    </form>
@endsection

resources/views/kepengurusan/warga/edit.blade.php
@extends("layouts.app")

@section('title', 'Ubah Warga')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Form Ubah Data Warga Green Semanggi Mangrove
    </p>
    <div class="alert alert-primary alert-has-icon">
        <div class="alert-icon"><i class="far fa-lightbulb"></i></div>
        <div class="alert-body">
            <div class="alert-title">Info</div>
            Jika tidak menemukan No. KK silahkan melakukan tambah data KK di <a href="{{ route('kartu_keluarga_warga.create') }}" class="badge badge-info">link ini</a>
        </div>
    </div>
    <form action="{{ route('warga.update', $warga->id_warga) }}" method="POST" enctype="multipart/form-data" novalidate>
        @method("PUT")
        @csrf
        @include("kepengurusan.warga._form")
    </form>
@endsection

resources/views/kepengurusan/warga/index.blade.php
@extends("layouts.app")

@section('title', 'Daftar Warga')
@section('content')
    <h2 class="section-title">@yield("title")</h2>
    <p class="section-lead">
        Halaman Pengelolaan Data Warga Green Semanggi Mangrove
    </p>
    <div class="col">
        <form action="{{ route('warga.export_dokumen') }}" id="export_dokumen" method="POST">
            @csrf
            <div class="form-group row">
                <select class="form-control col-12 col-md-2 col-lg-2 select2 @error('nama_cluster') is-invalid @enderror" name="nama_cluster">
                    <option value="">Pilih</option>
                    <option value="semua_cluster">Semua Cluster</option>
                    @foreach ($cluster as $data_cluster)
                        <option value="{{ $data_cluster->id_cluster }}">{{ $data_cluster->nama_cluster }}</option>
                    @endforeach
                </select>
                <button type="submit" form="export_dokumen" class="btn col-12 col-md-2 col-lg-2 btn-info">
                    <i class="fas fa-file-export"></i> Export Dokumen Warga
                </button>
            </div>
            @error('nama_cluster')
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
            @enderror
        </form>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col col-12 col-md-3 col-lg-3">
                    <div class="form-group">
                        <a href="{{ route('warga.create') }}" class="btn btn-icon btn-block icon-left btn-success">
                            <i class="fas fa-plus-circle"></i> Tambah Data Warga
                        </a>
                    </div>
                </div>
                <div class="col col-12 col-md-8 col-lg-8">
                    <form action="{{ route('warga.export_data') }}" id="export_data" method="POST">
                        <div class="form-group row">
                            @csrf
                            <select class="form-control col-12 col-md-3 col-lg-3 select2 @error('cluster') is-invalid @enderror" name="cluster">
                                <option value="">Pilih</option>
                                @foreach ($cluster as $data_cluster)
                                    <option value="{{ $data_cluster->id_cluster }}">{{ $data_cluster->nama_cluster }}</option>
                                @endforeach
                            </select>
                            <button type="submit" form="export_data" class="btn col-12 col-md-3 col-lg-3 btn-warning">
                                <i class="fas fa-file-export"></i> Export Data Warga
                            </button>
                        </div>
                        @error('cluster')
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                        @enderror
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div style="overflow: hidden;">
                        <table class="table table-striped" id="datatables-warga">
                            <thead>
                                <tr>
                                    <th>No KK</th>
                                    <th>NIK</th>
                                    <th>Nama Lengkap</th>
                                    <th>Nomor Telepon</th>
                                    <th class="noExport">Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($warga as $data_warga)
                                    <tr>
                                        <td>{{ $data_warga->kartukeluarga->no_kk }}</td>
                                        <td>{{ $data_warga->nik }}</td>
                                        <td>{{ $data_warga->nama_lengkap }}</td>
                                        <td><a href="http://api.whatsapp.com/send?phone={{ $data_warga->nomor_telepon }}" target="_blank">{{ $data_warga->nomor_telepon }}</a></td>
                                        <td>
                                            <a href="{{ route('warga.show', $data_warga->id_warga) }}" class="btn btn-sm btn-icon btn-info mb-1">
                                                <i class="far fa-eye hidden-lg"></i> Lihat
                                            </a>
                                            <a href="{{ route('warga.edit', $data_warga->id_warga) }}" class="btn btn-sm btn-icon btn-warning mr-1 ml-1 mb-1">
                                                <i class="far fa-edit "></i> Ubah
                                            </a>
                                            <form style="all: unset" action="{{ route('warga.destroy', $data_warga->id_warga) }}" id="form_delete_{{ $data_warga->id_warga }}" data-id="{{ $data_warga->nik }}" method="POST">
                                                @method("DELETE")
                                                @csrf
                                                <button type="button" onclick="deleteconfirm('form_delete_{{ $data_warga->id_warga }}')" class="btn btn-sm btn-icon btn-danger mb-1"><i class="far fa-trash-alt"></i>
                                                    Hapus
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css-library')
    <link rel="stylesheet" href="{{ asset('assets/modules/datatables/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/modules/select2/dist/css/select2.min.css') }}">
@endpush


@push('js-library')
    <script src="{{ asset('assets/modules/datatables/datatables.min.js') }}"></script>
    <script src="{{ asset('assets/modules/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('assets/modules/jquery-ui/jquery-ui.min.js') }}"></script>

    <script src="{{ asset('assets/modules/sweetalert/sweetalert.min.js') }}"></script>
@endpush


@push('js-template')
    <script>
        $(document).ready(function() {
            $('.select2').select2();

            $("#datatables-warga").dataTable({
                responsive: true,
                paging: true,
                ordering: true,
                info: true,
                filter: true,
                length: true,
                processing: true,
                deferRender: true,
                autoWidth: false,
                language: {
                    url: "{{ asset('assets/modules/datatables/lang/id.json') }}"
                },
                responsive: {
                    details: {
                        display: $.fn.dataTable.Responsive.display.modal({
                            header: function(row) {
                                var data = row.data();
                                return 'Data Warga ';
                            }
                        }),
                        renderer: $.fn.dataTable.Responsive.renderer.tableAll()
                    }
                },
                columnDefs: [{
                        targets: -1,
                        visible: true
                    },
                    {
                        "width": "28%",
                        "targets": -1
                    },
                    {
                        orderable: false,
                        targets: -1
                    },
                ],
            });
        });

        function deleteconfirm(form) {
            var id = $('#' + form).attr('data-id');
            swal({
                title: 'Apakah Anda Yakin Menghapus data : ' + id + '?',
                text: 'Anda Tidak Akan Dapat Mengembalikannya!',
                icon: 'warning',
                buttons: ["Batal", "Ya, Hapus Data!"],
                dangerMode: true,
            }).then((willDelete) => {
                if (willDelete) {
                    $('#' + form).submit();
                }
            });
        }
    </script>
@endpush

resources/views/kepengurusan/warga/show.blade.php
@extends("layouts.app")

@section('title', 'Detail Warga')
@section('content')
    <h2 class="section-title">Lihat @yield("title")</h2>
    <p class="section-lead">
        Halaman Pengelolaan Data Warga Green Semanggi Mangrove
    </p>
    <div class="card author-box card-primary">
        <div class="card-body">
            <div>
                <div class="author-box-name">
                    <a href="#">{{ $warga->nama_lengkap }}</a>
                </div>
                <div class="author-box-job">No KK. {{ $warga->no_kk }}</div>
                <div class="w-100 d-sm-none"></div>
            </div>
            <div class="author-box-description">
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table table-striped table-sm">
                                <tr>
                                    <th>NIK</th>
                                    <td class="absorbing-column">{{ $warga->nik }}</td>
                                </tr>
                                <tr>
                                    <th>Nama Lengkap</th>
                                    <td class="absorbing-column">{{ $warga->nama_lengkap }}</td>
                                </tr>
                                <tr>
                                    <th>Jenis Kelamin</th>
                                    <td class="absorbing-column">{{ $warga->jenis_kelamin }}</td>
                                </tr>
                                <tr>
                                    <th>Agama</th>
                                    <td class="absorbing-column">{{ $warga->agama }}</td>
                                </tr>
                                <tr>
                                    <th>No Telepon</th>
                                    <td class="absorbing-column"><a href="http://api.whatsapp.com/send?phone={{ $warga->nomor_telepon }}" target="_blank">{{ $warga->nomor_telepon }}</a></td>
                                </tr>
                                <tr>
                                    <th>Pekerjaan</th>
                                    <td class="absorbing-column">{{ $warga->pekerjaan }}</td>
                                </tr>
                                <tr>
                                    <th>Alamat KTP</th>
                                    <td class="absorbing-column">{{ $warga->alamat_ktp }}</td>
                                </tr>
                                @foreach ($perumahan as $key => $data_perumahan)
                                    <tr>
                                        <th>Alamat Perumahan {{ $loop->iteration }}</th>
                                        <td>{{ $data_perumahan->cluster->nama_cluster }}, {{ $data_perumahan->blok_perumahan }}-{{ $data_perumahan->nama_perumahan }}</td>
                                    </tr>
                                @endforeach
                                <tr>
                                    <th>Status Kawin</th>
                                    <td class="absorbing-column">{{ $warga->status_kawin }}</td>
                                </tr>
                                <tr>
                                    <th>Tempat/Tgl. Lahir</th>
                                    <td class="absorbing-column">{{ $warga->tempat_lahir }}, {{ \Carbon\Carbon::parse($warga->tanggal_lahir)->isoFormat('D MMMM Y') }}</td>
                                </tr>
                                <tr>
                                    <th>Gol. Darah</th>
                                    <td class="absorbing-column">{{ $warga->golongan_darah }}</td>
                                </tr>
                                <tr>
                                    <th>Status Hubungan Keluarga</th>
                                    <td class="absorbing-column">{{ $warga->status_hubungan_keluarga }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col col-sm-12 col-lg-2 col-md-2 ">
                        <strong>File Kependudukan:</strong>
                    </div>
                    <div class="col col-sm-12 col-lg-6 col-md-6">
                        <div class="btn-group btn-group-sm" role="group">
                            <a href="#" class="btn btn-primary" data-toggle="modal" data-target=".modal-file-kk">File KK</a>
                            <a href="#" class="btn btn-primary" data-toggle="modal" data-target=".modal-file-ktp">File KTP</a>
                            <a href="#" class="btn btn-primary @if (empty($warga->file_pernikahan)) disabled @endif" data-toggle="modal" data-target=".modal-file-pernikahan">File Pernikahan</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('modal')
    <div class="modal fade modal-file-kk" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">File Kartu Keluarga</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body modal-kk">
                    <div class="embed-responsive embed-responsive-16by9 d-none d-lg-block d-xl-block">
                        <object data="{{ asset('storage/assets/pdf/dokumen_kk/' . $warga->file_kk) }}" type="application/pdf"></object>
                    </div>
                    <div class="alert alert-warning d-block d-sm-none">
                        Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href="{{ asset('storage/assets/pdf/dokumen_kk/' . $warga->file_kk) }}" download>sini</a>
                    </div>
                </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-primary">Save changes</button> --}}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-file-ktp" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">File KTP</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body modal-ktp">
                    <div class="embed-responsive embed-responsive-16by9 d-none d-lg-block d-xl-block">
                        <object data="{{ asset('storage/assets/pdf/dokumen_ktp/' . $warga->file_ktp) }}" type="application/pdf"></object>
                    </div>
                    <div class="alert alert-warning d-block d-sm-none">
                        Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href="{{ asset('storage/assets/pdf/dokumen_ktp/' . $warga->file_ktp) }}" download>sini</a>
                    </div>
                </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-primary">Save changes</button> --}}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade modal-file-pernikahan" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">File Pernikahan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Tutup">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body modal-pernikahan">
                    @if (!empty($warga->file_pernikahan))
                        <div class="embed-responsive embed-responsive-16by9 d-none d-lg-block d-xl-block">
                            <object data="{{ asset('storage/assets/pdf/dokumen_pernikahan/' . $warga->file_pernikahan) }}" type="application/pdf"></object>
                        </div>
                        <div class="alert alert-warning d-block d-sm-none">
                            Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href="{{ asset('storage/assets/pdf/dokumen_pernikahan/' . $warga->file_pernikahan) }}" download>sini</a>
                        </div>
                    @else
                        <div class="alert alert-danger alert-has-icon">
                            <div class="alert-icon"><i class="fas fa-praying-hands"></i></div>
                            <div class="alert-body">
                                <div class="alert-title">Mohon Maaf</div>
                                File dokumen ini tidak tersedia
                            </div>
                        </div>
                    @endif
                </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-primary">Save changes</button> --}}
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('css-template')
    <style>
        table {
            table-layout: auto !important;
            border-collapse: collapse !important;
            width: 100% !important;
        }

        table .absorbing-column {
            width: 80% !important;
            align-content: left;
        }

    </style>
@endpush

@push('js-library')
    <script src="{{ asset('assets/modules/sweetalert/sweetalert.min.js') }}"></script>
@endpush

@push('js-template')
    <script>
        $(document).ready(function() {
            $(".modal-file-kk").on("hidden.bs.modal", function() {
                $(".modal-kk").html("");
                $(".modal-kk").html("<div class='embed-responsive embed-responsive-4by3 d-none d-lg-block d-xl-block'><object data='{{ asset('storage/assets/pdf/dokumen_kk/' . $warga->file_kk) }}' type='application/pdf'></object></div><div class='alert alert-warning d-block d-sm-none'>Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href='{{ asset('storage/assets/pdf/dokumen_kk/' . $warga->file_kk) }}' download>sini</a></div>");
            });

            $(".modal-file-ktp").on("hidden.bs.modal", function() {
                $(".modal-ktp").html("");
                $(".modal-ktp").html("<div class='embed-responsive embed-responsive-4by3 d-none d-lg-block d-xl-block'><object data='{{ asset('storage/assets/pdf/dokumen_ktp/' . $warga->file_ktp) }}' type='application/pdf'></object></div><div class='alert alert-warning d-block d-sm-none'>Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href='{{ asset('storage/assets/pdf/dokumen_ktp/' . $warga->file_ktp) }}' download>sini</a></div>");
            });

            $(".modal-file-pernikahan").on("hidden.bs.modal", function() {
                $(".modal-pernikahan").html("@if (!empty($warga->file_pernikahan)) <div class='embed-responsive embed-responsive-16by9 d-none d-lg-block d-xl-block'><object data='{{ asset('storage/assets/pdf/dokumen_pernikahan/' . $warga->file_pernikahan) }}' type='application/pdf'></object></div><div class='alert alert-warning d-block d-sm-none'>Mohon Maaf. File Tidak Dapat Ditampilkan, Silahkan Unduh di <a href='{{ asset('storage/assets/pdf/dokumen_pernikahan/' . $warga->file_pernikahan) }}' download>sini</a></div>@else<div class='alert alert-danger alert-has-icon'><div class='alert-icon'><i class='fas fa-praying-hands'></i></div><div class='alert-body'><div class='alert-title'>Mohon Maaf</div>File dokumen ini tidak tersedia</div></div>@endif");
            });
        });
    </script>
@endpush